services:
  webserver:
    environment:
      HOST: ""
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./data:/usr/src/app/data
    restart: unless-stopped