services:
  webserver:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./data:/usr/src/app/data
      - ./target:/usr/src/app/target
    restart: unless-stopped